{
 "title": "Charges v2",
 "tags": [
  "tesla",
  "le个人汉化"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "locations",
    "label": "Locations",
    "query": "SELECT \n\tDISTINCT COALESCE(geo.name, CONCAT_WS(', ', COALESCE(addr.name, nullif(CONCAT_WS(' ', addr.road, addr.house_number), '')), addr.city)) AS location\nFROM\n\tcharging_processes cp\nLEFT JOIN addresses addr ON cp.address_id = addr.id\nLEFT JOIN geofences geo ON cp.geofence_id = geo.id\nWHERE cp.car_id = $car_id\nORDER BY 1 ASC"
   },
   { "name": "charge_type", "label": "Charge type", "query": "AC, DC" },
   {
    "name": "temp_unit",
    "query": "select unit_of_temperature from settings limit 1;"
   },
   {
    "name": "preferred_range",
    "query": "select preferred_range from settings limit 1;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   },
   { "name": "min_duration_min", "label": "Min duration (minutes)", "query": "0" },
   { "name": "cost", "label": "Min cost", "query": "0" }
  ]
 },
 "panels": [
  { "title": "$car_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "car_id" },
  {
   "title": "Charges",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n    SELECT\n        (round(extract(epoch FROM start_date) - 10) * 1000) AS start_date_ts,\n        (round(extract(epoch FROM end_date) + 10) * 1000) AS end_date_ts,\n        start_date,\n        end_date,\n        COALESCE(g.name, CONCAT_WS(', ', COALESCE(a.name, nullif(CONCAT_WS(' ', a.road, a.house_number), '')), a.city)) AS address,\n        g.name as geofence_name,\n        g.id as geofence_id,\n        p.latitude,\n        p.longitude,\n        cp.charge_energy_added,\n        cp.charge_energy_used,\n        duration_min,\n        start_battery_level,\n        end_battery_level,\n        start_[[preferred_range]]_range_km,\n        end_[[preferred_range]]_range_km,\n        outside_temp_avg,\n        cp.id,\n        lag(end_[[preferred_range]]_range_km) OVER (ORDER BY start_date) - start_[[preferred_range]]_range_km AS range_loss,\n        p.odometer - lag(p.odometer) OVER (ORDER BY start_date) AS distance,\n        cars.efficiency,\n        cp.car_id,\n        cost,\n        max(c.charger_voltage) as max_charger_voltage,\n        CASE WHEN (mode() within group (order by c.fast_charger_present)) = true \n          THEN 'DC' \n          ELSE 'AC' \n        END AS charge_type\n    FROM\n        charging_processes cp\n\t  LEFT JOIN charges c ON cp.id = c.charging_process_id\n    LEFT JOIN positions p ON p.id = cp.position_id\n    LEFT JOIN cars ON cars.id = cp.car_id\n    LEFT JOIN addresses a ON a.id = cp.address_id\n    LEFT JOIN geofences g ON g.id = geofence_id\nWHERE \n    cp.car_id = $car_id AND\n    $__timeFilter(start_date) AND\n    (cp.charge_energy_added IS NULL OR cp.charge_energy_added > 0) AND\n    ('all_locations' in ($locations) OR COALESCE(g.name, CONCAT_WS(', ', COALESCE(a.name, nullif(CONCAT_WS(' ', a.road, a.house_number), '')), a.city)) in ($locations))\nGROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10,11,12,13,14,15,16,17,18,21,p.odometer\nORDER BY\n    start_date\n)\nSELECT\n    start_date_ts,\n    end_date_ts,\n    CASE WHEN geofence_id IS NULL THEN CONCAT('new?lat=', latitude, '&lng=', longitude)\n         WHEN geofence_id IS NOT NULL THEN CONCAT(geofence_id, '/edit')\n    END as path,\n    car_id,\n    id,\n    -- Columns\n    start_date,\n    end_date,\n    address,    \n    charge_type,\n    duration_min,\n    cost,\n    cost / NULLIF(greatest(charge_energy_added, charge_energy_used), 0) as cost_per_kwh,\n    charge_energy_added,\n    charge_energy_used,\n    CASE WHEN charge_energy_used IS NULL THEN NULL ELSE LEAST(charge_energy_added / NULLIF(charge_energy_used, 0), 1.0) END as charging_efficiency,\n    convert_celsius(outside_temp_avg, '$temp_unit') AS outside_temp_avg_$temp_unit,\n    charge_energy_added * 60 / NULLIF (duration_min, 0) AS charge_energy_added_per_hour,\n    convert_km((end_[[preferred_range]]_range_km - start_[[preferred_range]]_range_km) * 60 / NULLIF (duration_min, 0), '$length_unit') AS range_added_per_hour_$length_unit,\n    start_battery_level,\n    end_battery_level,\n    convert_km(distance::numeric, '$length_unit') AS distance_$length_unit\n FROM\n    data\nWHERE\n    (distance >= 0 OR distance IS NULL)\n    AND duration_min >= '$min_duration_min'\n    AND CASE WHEN $cost = '0'\n\t\t  THEN (cost IS NULL OR cost >= '0')\n\t\t  ELSE cost >= '$cost'\n\t  END\n    AND CASE WHEN 'all_types' = $charge_type\n  \t\tTHEN 1 = 1\n  \t\tELSE charge_type = $charge_type\n  \tEND\nORDER BY\n  start_date DESC;"
    }
   ]
  },
  {
   "title": "Energy added",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT cp.start_date as \"time\", cp.charge_energy_added\nFROM charging_processes cp\nLEFT JOIN addresses a ON a.id = cp.address_id\nLEFT JOIN geofences g ON g.id = cp.geofence_id\nWHERE \n  $__timeFilter(cp.start_date) \n  AND cp.car_id = $car_id\n  AND ('all_locations' in ($locations) OR COALESCE(g.name, CONCAT_WS(', ', COALESCE(a.name, nullif(CONCAT_WS(' ', a.road, a.house_number), '')), a.city)) in ($locations))\nORDER BY cp.start_date;"
    }
   ]
  },
  {
   "title": "Energy used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT cp.start_date as \"time\", greatest(cp.charge_energy_added, cp.charge_energy_used)\nFROM charging_processes cp\nLEFT JOIN addresses a ON a.id = cp.address_id\nLEFT JOIN geofences g ON g.id = cp.geofence_id\nWHERE \n  $__timeFilter(cp.start_date) \n  AND cp.car_id = $car_id\n  AND ('all_locations' in ($locations) OR COALESCE(g.name, CONCAT_WS(', ', COALESCE(a.name, nullif(CONCAT_WS(' ', a.road, a.house_number), '')), a.city)) in ($locations))\nORDER BY cp.start_date;"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT cp.start_date as \"time\", cp.cost\nFROM charging_processes cp\nLEFT JOIN addresses a ON a.id = cp.address_id\nLEFT JOIN geofences g ON g.id = cp.geofence_id\nWHERE \n  $__timeFilter(cp.start_date) \n  AND cp.car_id = $car_id\n  AND ('all_locations' in ($locations) OR COALESCE(g.name, CONCAT_WS(', ', COALESCE(a.name, nullif(CONCAT_WS(' ', a.road, a.house_number), '')), a.city)) in ($locations))\nORDER BY cp.start_date;"
    }
   ]
  }
 ]
}