{
 "title": "Locations v2",
 "tags": [
  "tesla",
  "le个人汉化"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   },
   { "name": "address_filter", "label": "Address" }
  ]
 },
 "panels": [
  {
   "title": "Total addresses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(end_address_id))\nFROM drives\nWHERE \n\tcar_id = $car_id\n\tAND end_address_id IS NOT NULL"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(a.city))\nFROM drives d\nLEFT JOIN addresses a ON a.id = d.end_address_id\nWHERE \n\td.car_id = $car_id\n\tAND d.end_address_id IS NOT NULL"
    }
   ]
  },
  {
   "title": "States",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(a.state))\nFROM drives d\nLEFT JOIN addresses a ON a.id = d.end_address_id\nWHERE \n\td.car_id = $car_id\n\tAND d.end_address_id IS NOT NULL"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT(a.country))\nFROM drives d\nLEFT JOIN addresses a ON a.id = d.end_address_id\nWHERE \n\td.car_id = $car_id\n\tAND d.end_address_id IS NOT NULL"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT city, count(*) as \"# addresses\"\nFROM drives d\nLEFT JOIN addresses a ON a.id = d.end_address_id\nWHERE \n\td.car_id = $car_id\n\tAND d.end_address_id IS NOT NULL\n\tAND a.city IS NOT NULL\nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "States",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT state, count(*) as \"# addresses\"\nFROM drives d\nLEFT JOIN addresses a ON a.id = d.end_address_id\nWHERE \n\td.car_id = $car_id\n\tAND d.end_address_id IS NOT NULL\n\tAND a.state IS NOT NULL\nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Last locations visited",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tMAX(end_date) as \"Date\",\n  \tCOUNT(*) as visited,\n\tCOALESCE(g.name, array_to_string(((string_to_array(a.display_name, ', ', ''))[0:2]), ', ')) AS \"Address\",\n\tCOALESCE(city, neighbourhood) as \"City\",\n\ta.country AS \"Country\"\nFROM drives t\nINNER JOIN addresses a ON end_address_id = a.id\nLEFT JOIN geofences g ON end_geofence_id = g.id\nWHERE \n\t(a.display_name ILIKE '%$address_filter%' OR g.name ilike '%$address_filter%') \n\tAND car_id = $car_id\nGROUP BY 3, 4, 5\nORDER BY visited DESC\nLIMIT 100"
    }
   ]
  }
 ]
}