{
 "title": "充电曲线DC Charging Curves by Carrier",
 "tags": [
  "le个人汉化",
  "tesla"
 ],
 "time": { "from": "now-1M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   },
   { "name": "carrier", "label": "Carrier" }
  ]
 },
 "panels": [
  {
   "title": "Charger Carrier Contains: $carrier",
   "type": "natel-plotly-panel",
   "gridPos": { "h": 16, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  c.battery_level as \"SOC [%]\",\r\n  round(avg(c.charger_power), 0) as \"Power [kW]\",\r\n  c.charging_process_id as \"charging_process_id\",\r\n  COALESCE(g.name, a.name) || ' ' || to_char(c.date, 'YYYY-MM-dd') as \"Charge\"\r\nFROM\r\n  charges c\r\nJOIN charging_processes p ON p.id = c.charging_process_id \r\nJOIN addresses a ON a.id = p.address_id\r\nLEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  $__timeFilter(date)\r\n AND p.car_id = $car_id\r\n AND c.fast_charger_present\r\n AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY c.battery_level, c.charging_process_id, a.name, g.name, to_char(c.date, 'YYYY-MM-dd')"
    },
    {
     "rawSql": "SELECT\n  c.battery_level as \"B - SOC [%]\",\n  PERCENTILE_CONT(0.5) WITHIN GROUP(ORDER BY charger_power) as \"B - Avg Power [kW]\"\nFROM\n  charges c\nJOIN charging_processes p ON p.id = c.charging_process_id \nJOIN addresses a ON a.id = p.address_id\nLEFT JOIN geofences g ON g.id = p.geofence_id\nWHERE\n  $__timeFilter(date)\n AND p.car_id = $car_id\n AND c.fast_charger_present\n AND COALESCE(g.name, a.name) ILIKE '%$carrier%'\nGROUP BY battery_level"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 16, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\nSELECT\r\n  COALESCE(g.name, a.name) AS name\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id, g.name, a.name\r\n)\r\nSELECT name AS \"Charger Carrier\" FROM data GROUP BY name\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "充电增加",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n AVG(p.charge_energy_added)\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id"
    }
   ]
  },
  {
   "title": "平均使用",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n AVG(p.charge_energy_used)\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id"
    }
   ]
  },
  {
   "title": "充电用时",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n AVG(duration_min)\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\n"
    }
   ]
  },
  {
   "title": "充电费用",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n AVG(p.cost)\r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id"
    }
   ]
  },
  {
   "title": "每度电价格",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\r\nSELECT\r\n AVG(p.charge_energy_used) AS charge_energy_used, AVG(p.cost) AS cost \r\nFROM charging_processes p\r\n    LEFT JOIN charges c ON c.charging_process_id = p.id\r\n    LEFT JOIN addresses a ON a.id = p.address_id\r\n    LEFT JOIN geofences g ON g.id = p.geofence_id\r\nWHERE\r\n  p.car_id = $car_id \r\n  AND $__timeFilter(start_date)\r\n  AND c.fast_charger_present\r\n  AND COALESCE(g.name, a.name) ILIKE '%$carrier%' \r\nGROUP BY p.id\r\n)\r\nSELECT AVG(cost) / AVG(charge_energy_used) cost_kwh  FROM data"
    }
   ]
  },
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
     "options": {
      "content": "#### DC Charing curves by Carrier\n\nTo analyse data with this dashboard, it's important that you \nhave Geo-Fences added related with the name of the carrier\nyou have recharged your car, or you may want to edit \nperiodically the **name** field of the **addresses** table,\nso that it contains its name. \n\nFor example, if **Teslamate** geolocates the name as \n*\"Esso Purley Way\"* you may modify it to \n*\"Esso Purley Way - IONITY\"* or *\"IONITY Esso Purley Way\"*, \nthen you can filter using\nthe textbox above as **IONITY** to show all the charging curves\nof all charging sessions at that carrier."
     },
     "targets": [
      {
       "rawSql": "SELECT\n  start_date AS \"time\",\n  start_km\nFROM drives\nWHERE\n  $__timeFilter(start_date)\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}