{
 "title": "电池健康v2Battery Health",
 "tags": [
  "tesla",
  "le个人汉化"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "preferred_range",
    "query": "select  preferred_range from settings;"
   },
   {
    "name": "battery_capacity",
    "query": "WITH lastCharges AS (\n\tSELECT (100.0 * charge_energy_added) / (end_battery_level - start_battery_level)\n\tFROM charging_processes\n\tWHERE \n\t\tcharge_energy_added >= 10\n\t\tAND car_id = $car_id\n\tORDER BY end_date DESC\n\tLIMIT 5\n)\nSELECT * FROM lastCharges \nORDER BY 1 DESC\nLIMIT 1"
   },
   {
    "name": "degradation",
    "query": "SELECT AVG(data.degradation) FROM\n(\n\tSELECT 100 - convert_km(((end_rated_range_km * 100.0)/(end_battery_level * $max_range / 100.0)), '$length_unit')::float as degradation\n\tFROM charging_processes \n\tWHERE \n\t\tcar_id = $car_id \n\t\tAND end_date IS NOT NULL \n\t\tAND charge_energy_added > 10 \n\tORDER BY end_date DESC\n\tLIMIT 50\n) AS data\n"
   },
   {
    "name": "max_range",
    "query": "WITH projected_range AS (\n\tSELECT\n\t\t$__timeGroup(date, 1d) AS time,\n\t\tconvert_km((sum(rated_battery_range_km) / nullif(sum(coalesce(usable_battery_level, battery_level)),0) * 100)::numeric, '$length_unit') AS \"Projected rated range [$length_unit]\"\n\tFROM\n\t\t(\n\t\t\tSELECT \n\t\t\t\tbattery_level, usable_battery_level, date, rated_battery_range_km\n    \t\tFROM positions\n    \t\tWHERE\n\t\t\t\tcar_id = $car_id\n\t\t\t\tAND ideal_battery_range_km IS NOT null\n    \t\tUNION ALL\n    \t\t\tSELECT \n\t\t\t\t\tbattery_level, coalesce(usable_battery_level, battery_level) as usable_battery_level, date, rated_battery_range_km\n\t\t    \tFROM charges c\n    \t\t\tJOIN\n      \t\t\t\tcharging_processes p ON p.id = c.charging_process_id \n    \t\t\tWHERE\n       \t\t\t\tp.car_id = $car_id\n    \t) AS data\n\tGROUP BY 1\n\tHAVING convert_km((sum(rated_battery_range_km) / nullif(sum(coalesce(usable_battery_level, battery_level)),0) * 100)::numeric, '$length_unit') IS NOT null\n\tORDER BY 2 DESC\n\tLIMIT 1\n)\nSELECT \"Projected rated range [$length_unit]\" FROM projected_range "
   },
   {
    "name": "degradation_period",
    "label": "Period for the calculation of degradation",
    "query": "1 week,2 weeks,1 month"
   }
  ]
 },
 "panels": [
  {
   "title": "Battery capacity progression",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE \n    WHEN '$degradation_period' = '1 week' THEN $__timeGroup(date, '1w')\n    WHEN '$degradation_period' = '2 weeks' THEN $__timeGroup(date, '2w')\n    ELSE $__timeGroup(date, '1M')\n  END AS time,\n\tconvert_km((sum([[preferred_range]]_battery_range_km) / nullif(sum(coalesce(usable_battery_level,battery_level)),0) * 100)::numeric, '$length_unit') \n\t* ($battery_capacity + ($battery_capacity * $degradation / 100.0)) / $max_range AS \"kWh\"\nFROM\n\t(\n    SELECT \n      battery_level, usable_battery_level, date, rated_battery_range_km, ideal_battery_range_km, outside_temp\n    FROM positions\n    WHERE\n      car_id = $car_id \n      AND $__timeFilter(date) \n      AND ideal_battery_range_km is not null\n    UNION ALL\n    SELECT \n      battery_level, coalesce(usable_battery_level,battery_level) as usable_battery_level, date, \n      rated_battery_range_km, ideal_battery_range_km, outside_temp\n    FROM charges c\n    JOIN\n      charging_processes p ON p.id = c.charging_process_id \n    where\n      p.car_id = $car_id\n    ) AS data\nGROUP BY 1\nHAVING \n  convert_km((sum([[preferred_range]]_battery_range_km) / nullif(sum(coalesce(usable_battery_level,battery_level)),0) * 100)::numeric, '$length_unit') IS NOT NULL\nORDER BY 1, 2  DESC"
    }
   ]
  },
  {
   "title": "Estimated degradation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  $degradation as \"Degradation\""
    }
   ]
  },
  {
   "title": "Complete battery cycles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH charge AS (\n  SELECT\n  \tsum(charge_energy_added) AS total_energy\n  FROM\n  \tcharging_processes\n  WHERE\n  \tcar_id = $car_id\n)\nSELECT  \n  total_energy / ($battery_capacity * (1 + ($degradation / 100)))\nFROM charge"
    }
   ]
  },
  {
   "title": "Number of charges",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcount(*)\nFROM\n\tcharging_processes\nWHERE\n\tcharge_energy_added > 0.01\n\tAND car_id = $car_id;"
    }
   ]
  },
  {
   "title": "Battery Health",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  (100 - $degradation) as \"Battery Health (%)\""
    }
   ]
  },
  {
   "title": "Current battery capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \n  $battery_capacity AS battery_capacity"
    }
   ]
  },
  {
   "title": "Current capacity",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "(\n  SELECT date, usable_battery_level * $battery_capacity / 100 as kWh\n  FROM positions\n  WHERE car_id = $car_id\n  ORDER BY date DESC\n  LIMIT 1\n)\nUNION\nSELECT date, usable_battery_level * $battery_capacity / 100 as kWh\nFROM charges c\nJOIN charging_processes p ON p.id = c.charging_process_id\nWHERE p.car_id = $car_id\nORDER BY date DESC\nLIMIT 1"
    },
    {
     "rawSql": "SELECT  \n  $battery_capacity AS battery_capacity"
    }
   ]
  },
  {
   "title": "AC/DC – Energy added",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n  SELECT\n\t\tcp.id,\n\t\tcp.charge_energy_added,\n\t\tCASE WHEN NULLIF(mode() within group (order by charger_phases),0) is null THEN 'DC'\n\t\t\t\t ELSE 'AC'\n\t\tEND AS current,\n\t\tcp.charge_energy_used\n\tFROM charging_processes cp\n  RIGHT JOIN charges ON cp.id = charges.charging_process_id\n  WHERE\n\t  cp.car_id = $car_id\n\t  AND cp.charge_energy_added > 0.01\n  GROUP BY 1,2\n)\nSELECT\n\tnow() AS time,\n\tsum(greatest(charge_energy_added, charge_energy_used)) AS value,\n\tcurrent AS metric\nFROM data\nGROUP BY 3\nORDER BY metric DESC;"
    }
   ]
  },
  {
   "title": "Current battery level",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "%",
     "query": "SELECT last(\"soc\") FROM \"ovms\" WHERE $timeFilter",
     "rawSql": "(SELECT usable_battery_level, date\n  FROM positions\n  WHERE car_id = $car_id\n  ORDER BY date DESC\n  LIMIT 1\n)\nUNION\n  SELECT usable_battery_level, date\n  FROM charges c\n  JOIN charging_processes p ON p.id = c.charging_process_id\n  WHERE p.car_id = $car_id\n  ORDER BY date DESC\n  LIMIT 1\n",
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "ovms_v_b_soc" }
     ]
    }
   ]
  },
  {
   "title": "Energy summary",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  inserted_at AS \"time\",\n  efficiency\nFROM cars\nWHERE\n  $__timeFilter(inserted_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Energy added",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(charge_energy_added)\nFROM\n\tcharging_processes\nWHERE\n\tcar_id = $car_id \n\tAND charge_energy_added > 0.01\n"
    }
   ]
  },
  {
   "title": "Energy used to recharge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tSUM(charge_energy_used)\nFROM\n\tcharging_processes\nWHERE\n\tcar_id = $car_id \n\tAND charge_energy_added > 0.01\n"
    }
   ]
  },
  {
   "title": "Recharging efficiency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\t( SUM(charge_energy_added) * 100 / SUM(charge_energy_used) )\nFROM\n\tcharging_processes\nWHERE\n\tcar_id = $car_id \n\tAND charge_energy_added > 0.01\n"
    }
   ]
  },
  {
   "title": "Mileage summary",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  inserted_at AS \"time\",\n  efficiency\nFROM cars\nWHERE\n  $__timeFilter(inserted_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select convert_km(odometer::numeric, '$length_unit')  as \"odometer_$length_unit\"\nfrom positions \nwhere car_id = $car_id \norder by date desc \nlimit 1;"
    }
   ]
  },
  {
   "title": "Current range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__time(date), range as \"range_$length_unit\"\nFROM (\n\t(\n\t  SELECT date, convert_km(rated_battery_range_km, '$length_unit') AS range\n\t  FROM positions\n\t  WHERE car_id = $car_id AND rated_battery_range_km IS NOT NULL\n    ORDER BY date DESC\n\t  LIMIT 1\n\t)\n\tUNION ALL\n\t(\n  \tSELECT date, convert_km([[preferred_range]]_battery_range_km, '$length_unit') AS range\n  \tFROM charges c\n  \tJOIN charging_processes p ON p.id = c.charging_process_id\n  \tWHERE p.car_id = $car_id\n  \tORDER BY date DESC\n  \tLIMIT 1\n\t)\n) AS data\nORDER BY date DESC\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Current MAX range",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__time(date), (range * 100.0 / battery_level) as \"max_range_$length_unit\"\nFROM (\n\t(SELECT date, convert_km(rated_battery_range_km, '$length_unit') AS range, usable_battery_level as battery_level\n\tFROM positions\n\tWHERE car_id = $car_id AND rated_battery_range_km IS NOT NULL\n  ORDER BY date DESC\n\tLIMIT 1)\n\tUNION ALL\n\t(SELECT date, convert_km([[preferred_range]]_battery_range_km, '$length_unit') AS range, usable_battery_level as battery_level\n\tFROM charges c\n\tJOIN charging_processes p ON p.id = c.charging_process_id\n\tWHERE p.car_id = $car_id\n\tORDER BY date DESC\n\tLIMIT 1)\n) AS data\nORDER BY date DESC\nLIMIT 1;"
    }
   ]
  }
 ]
}