{
 "title": "Charging Tops",
 "tags": [
  "tesla",
  "le个人汉化"
 ],
 "time": { "from": "now-10y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "suc_stats",
    "query": "SELECT\n\tCONCAT('{\n\t\t   \"totalEnergy\": ', COALESCE(SUM(charge_energy_added), 0),', \n\t\t   \"averageEnergy\": ',COALESCE(AVG(charge_energy_added), 0),', \n\t\t   \"totalTime\": ',COALESCE(SUM(duration_min), 0),', \n\t\t   \"averageTime\": ',COALESCE(AVG(duration_min), 0),', \n\t\t   \"totalCost\": ',COALESCE(SUM(cost), 0),', \n\t\t   \"averageCost\": ',COALESCE(AVG(cost), 0),'\n\t\t   }')\nFROM\n\tcharging_processes c\nLEFT JOIN addresses address ON c.address_id = address.id\nLEFT JOIN geofences geofence ON geofence_id = geofence.id\nWHERE\n\t$__timeFilter(end_date)\n\tAND car_id = $car_id\n\tAND (address.display_name ILIKE '%supercharger%' OR geofence.name ILIKE '%supercharger%');"
   },
   {
    "name": "dc_stats",
    "query": "SELECT\n\tCONCAT('{\n\t\t   \"totalEnergy\": ', COALESCE(SUM(charge_energy_added), 0),', \n\t\t   \"averageEnergy\": ',COALESCE(AVG(charge_energy_added), 0),', \n\t\t   \"totalTime\": ',COALESCE(SUM(duration_min), 0),', \n\t\t   \"averageTime\": ',COALESCE(AVG(duration_min), 0),', \n\t\t   \"totalCost\": ',COALESCE(SUM(cost), 0),', \n\t\t   \"averageCost\": ',COALESCE(AVG(cost), 0),'\n\t\t   }')\nFROM\n\tcharging_processes cp\nLEFT JOIN addresses addr ON cp.address_id = addr.id\nLEFT JOIN geofences geo ON cp.geofence_id = geo.id\nWHERE\n\tcp.id IN (\n\t\tSELECT c.charging_process_id \n\t  FROM charges c\n  \tLEFT JOIN charging_processes cp ON cp.id = c.charging_process_id\n  \tLEFT JOIN addresses addr ON addr.id = cp.address_id\n  \tLEFT JOIN geofences geo ON geo.id = geofence_id\n  \tWHERE \n  \t\t$__timeFilter(cp.start_date)\n  \t\tAND c.fast_charger_present IS true\n  \t\tAND c.charger_voltage = 2\n  \t\tAND cp.car_id = $car_id\n  \t\tAND CASE \n  \t\t\tWHEN (cp.geofence_id IS NOT NULL) THEN (addr.display_name NOT ILIKE '%supercharger%' AND geo.name NOT ILIKE '%supercharger%')\n  \t\t\tELSE addr.display_name NOT ILIKE '%supercharger%'\n  \t\tEND\n  \tGROUP BY 1\n\t);"
   },
   {
    "name": "ac_stats",
    "query": "SELECT\n\tCONCAT('{\n\t\t   \"totalEnergy\": ', COALESCE(SUM(charge_energy_added), 0),', \n\t\t   \"averageEnergy\": ',COALESCE(AVG(charge_energy_added), 0),', \n\t\t   \"totalTime\": ',COALESCE(SUM(duration_min), 0),', \n\t\t   \"averageTime\": ',COALESCE(AVG(duration_min), 0),', \n\t\t   \"totalCost\": ',COALESCE(SUM(cost), 0),', \n\t\t   \"averageCost\": ',COALESCE(AVG(cost), 0),'\n\t\t   }')\nFROM\n\tcharging_processes cp\nLEFT JOIN addresses addr ON cp.address_id = addr.id\nLEFT JOIN geofences geo ON cp.geofence_id = geo.id\nWHERE\n\tcp.id IN (\n\t\tSELECT c.charging_process_id \n\t  FROM charges c\n  \tLEFT JOIN charging_processes cp ON cp.id = c.charging_process_id\n  \tLEFT JOIN addresses addr ON addr.id = cp.address_id\n  \tLEFT JOIN geofences geo ON geo.id = geofence_id\n  \tWHERE \n  \t  $__timeFilter(cp.end_date)\n  \t\tAND c.fast_charger_present IS NOT true\n  \t\tAND c.charger_voltage != 2\n  \t\tAND cp.car_id = $car_id\n  \tGROUP BY 1\n\t);"
   }
  ]
 },
 "panels": [
  {
   "title": "Charged in total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tsum(charge_energy_added)\nFROM\n\tcharging_processes\nWHERE\n\t$__timeFilter(end_date)\n\tAND car_id = $car_id;\n"
    }
   ]
  },
  {
   "title": "AC/DC – Energy added",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n  SELECT\n\t\tcp.id,\n\t\tcp.charge_energy_added,\n\t\tCASE WHEN NULLIF(mode() within group (order by charger_phases),0) is null THEN 'DC'\n\t\t\t\t ELSE 'AC'\n\t\tEND AS current\n\tFROM charging_processes cp\n  RIGHT JOIN charges ON cp.id = charges.charging_process_id\n  WHERE\n\t  cp.car_id = $car_id\n\t  AND cp.charge_energy_added > 0.01\n\t  AND $__timeFilter(end_date)\n  GROUP BY 1,2\n)\nSELECT\n\tnow() AS time,\n\tsum(charge_energy_added) AS value,\n\tcurrent AS metric\nFROM data\nGROUP BY 3\nORDER BY metric DESC;"
    }
   ]
  },
  {
   "title": "Total charging cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tsum(cost)\nFROM\n\tcharging_processes\nWHERE\n\t$__timeFilter(end_date)\n\tAND car_id = $car_id;"
    }
   ]
  },
  {
   "title": "Cost per 100 $length_unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\n  SELECT sum(cost)\n  FROM charging_processes\n  WHERE $__timeFilter(end_date) AND car_id = $car_id\n) / (\n\tSELECT convert_km((max(odometer) - min(odometer))::numeric, '$length_unit')\n\tFROM positions\n\tWHERE $__timeFilter(date) AND car_id = $car_id\n) * 100"
    }
   ]
  },
  {
   "title": "Average cost per kWh",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT (\n  SELECT sum(cost)\n  FROM charging_processes\n  WHERE $__timeFilter(end_date) AND car_id = $car_id\n) / (\n  SELECT sum(greatest(charge_energy_added, charge_energy_used))\n  FROM charging_processes\n  WHERE $__timeFilter(end_date) AND car_id = $car_id\n)"
    }
   ]
  },
  {
   "title": "Free charged in total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tsum(charge_energy_added)\nFROM\n\tcharging_processes\nWHERE\n\t$__timeFilter(end_date)\n\tAND car_id = $car_id\n\tAND cost = 0;\n"
    }
   ]
  },
  {
   "title": "Charging cost at SuC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n\tSELECT c.charging_process_id \n\tFROM charges c\n\tLEFT JOIN charging_processes cp ON cp.id = c.charging_process_id\n\tLEFT JOIN addresses addr ON addr.id = cp.address_id\n\tLEFT JOIN geofences geo ON geo.id = geofence_id\n\tWHERE \n\t\tc.fast_charger_present IS true\n\t\tAND c.charger_voltage = 2\n\t\tAND cp.car_id = $car_id\n\t\tAND (addr.display_name LIKE '%Supercharger%' OR geo.name LIKE '%Supercharger%')\n\tGROUP BY 1\n)\nSELECT\n\tsum(cp.cost) as total\nFROM\n\tcharging_processes cp, data\nWHERE\n  $__timeFilter(end_date)\n  AND cp.cost IS NOT NULL\n  AND cp.id IN (data.charging_process_id);"
    }
   ]
  },
  {
   "title": "Cost in other DC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n\tSELECT c.charging_process_id \n\tFROM charges c\n\tLEFT JOIN charging_processes cp ON cp.id = c.charging_process_id\n\tLEFT JOIN addresses addr ON addr.id = cp.address_id\n\tLEFT JOIN geofences geo ON geo.id = geofence_id\n\tWHERE \n\t\tc.fast_charger_present IS true\n\t\tAND c.charger_voltage = 2\n\t\tAND cp.car_id = $car_id\n\t\tAND CASE \n\t\t\tWHEN (cp.geofence_id IS NOT NULL) THEN (addr.display_name NOT LIKE '%Supercharger%' AND geo.name NOT LIKE '%Supercharger%')\n\t\t\tELSE addr.display_name NOT LIKE '%Supercharger%'\n\t\tEND\n\tGROUP BY 1\n)\nSELECT\n\tsum(cp.cost) as total\nFROM\n\tcharging_processes cp, data\nWHERE\n  $__timeFilter(end_date)\n  AND cp.cost IS NOT NULL\n  AND cp.id IN (data.charging_process_id);"
    }
   ]
  },
  {
   "title": "AC Charging Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH data AS (\n\tSELECT c.charging_process_id \n\tFROM charges c\n\tLEFT JOIN charging_processes cp ON cp.id = c.charging_process_id\n\tWHERE \n\t\tc.fast_charger_present IS NOT true\n\t\tAND c.charger_voltage != 2\n\t\tAND cp.car_id = $car_id\n\tGROUP BY 1\n)\nSELECT\n\tsum(cp.cost) as total\nFROM\n\tcharging_processes cp, data\nWHERE\n  $__timeFilter(end_date)\n  AND cp.cost IS NOT NULL\n  AND cp.id IN (data.charging_process_id);"
    }
   ]
  },
  {
   "title": "Top recharges in SuperChargers",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOALESCE(geofence.name, CONCAT_WS(', ', COALESCE(address.name, nullif(CONCAT_WS(' ', address.road, address.house_number), '')), address.city)) AS location,\n\tCOUNT(*) AS total_recharges,\n\tCASE\n      WHEN SUM(charge_energy_added) < 1000 THEN SUM(charge_energy_added)::NUMERIC(4,0)::VARCHAR || ' kWh' \n      WHEN SUM(charge_energy_added) < 1000000 THEN (SUM(charge_energy_added) / 1000)::NUMERIC(9, 3)::VARCHAR || ' MWh' \n      WHEN SUM(charge_energy_added) >= 1000000 THEN (SUM(charge_energy_added) / 1000000)::NUMERIC(9, 3)::VARCHAR || ' GWh' \n  END as charge_energy_added,\n  AVG(charge_energy_added) as average_energy,\n  AVG(duration_min) as average_time,\n  SUM(cost) as cost\nFROM\n\tcharging_processes c\nLEFT JOIN addresses address ON c.address_id = address.id\nLEFT JOIN geofences geofence ON geofence_id = geofence.id\nWHERE\n\t$__timeFilter(end_date)\n\tAND car_id = $car_id\n\tAND (address.display_name ILIKE '%supercharger%' OR geofence.name ILIKE '%supercharger%')\nGROUP BY\n\t1\nORDER BY\n\tSUM(charge_energy_added) DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "SuC stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  inserted_at AS \"time\",\n  efficiency\nFROM cars\nWHERE\n  $__timeFilter(inserted_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ('$suc_stats'::json -> 'totalCost')::text::float AS total_cost,\n  ('$suc_stats'::json -> 'averageCost')::text::float AS average_cost"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ('$suc_stats'::json -> 'totalEnergy')::text::float  as total_energy,\n  ('$suc_stats'::json -> 'averageEnergy')::text::float  as average_energy"
    }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ('$suc_stats'::json -> 'totalTime')::text::float  as total_time,\n  ('$suc_stats'::json -> 'averageTime')::text::float  as average_time"
    }
   ]
  },
  {
   "title": "Top recharges in other DC stations",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOALESCE(geo.name, CONCAT_WS(', ', COALESCE(addr.name, nullif(CONCAT_WS(' ', addr.road, addr.house_number), '')), addr.city)) AS location,\n\tCOUNT(*) AS total_recharges,\n\tCASE\n      WHEN SUM(charge_energy_added) < 1000 THEN SUM(charge_energy_added)::NUMERIC(4,0)::VARCHAR || ' kWh' \n      WHEN SUM(charge_energy_added) < 1000000 THEN (SUM(charge_energy_added) / 1000)::NUMERIC(9, 3)::VARCHAR || ' MWh' \n      WHEN SUM(charge_energy_added) >= 1000000 THEN (SUM(charge_energy_added) / 1000000)::NUMERIC(9, 3)::VARCHAR || ' GWh' \n  END as charge_energy_added,\n  AVG(charge_energy_added) as average_energy,\n  AVG(duration_min) as average_time,\n  sum(cost) as cost\nFROM\n\tcharging_processes cp\nLEFT JOIN addresses addr ON cp.address_id = addr.id\nLEFT JOIN geofences geo ON cp.geofence_id = geo.id\nWHERE\n\tcp.id IN (\n\t\tSELECT c.charging_process_id \n\t  FROM charges c\n  \tLEFT JOIN charging_processes cp ON cp.id = c.charging_process_id\n  \tLEFT JOIN addresses addr ON addr.id = cp.address_id\n  \tLEFT JOIN geofences geo ON geo.id = geofence_id\n  \tWHERE \n  \t  $__timeFilter(cp.start_date)\n  \t\tAND c.fast_charger_present IS true\n  \t\tAND c.charger_voltage = 2\n  \t\tAND cp.car_id = $car_id\n  \t\tAND CASE \n  \t\t\tWHEN (cp.geofence_id IS NOT NULL) THEN (addr.display_name NOT ILIKE '%supercharger%' AND geo.name NOT ILIKE '%supercharger%')\n  \t\t\tELSE addr.display_name NOT ILIKE '%supercharger%'\n  \t\tEND\n  \tGROUP BY 1\n\t)\nGROUP BY\n\t1\nORDER BY\n\tSUM(charge_energy_added) DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Other DC stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  inserted_at AS \"time\",\n  efficiency\nFROM cars\nWHERE\n  $__timeFilter(inserted_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ('$dc_stats'::json -> 'totalCost')::text::float  as total_cost,\n  ('$dc_stats'::json -> 'averageCost')::text::float  as average_cost"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ('$dc_stats'::json -> 'totalEnergy')::text::float  as total_energy,\n  ('$dc_stats'::json -> 'averageEnergy')::text::float  as average_energy"
    }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ('$dc_stats'::json -> 'totalTime')::text::float  as total_time,\n  ('$dc_stats'::json -> 'averageTime')::text::float  as average_time"
    }
   ]
  },
  {
   "title": "Top recharges in AC stations",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCOALESCE(geo.name, CONCAT_WS(', ', COALESCE(addr.name, nullif(CONCAT_WS(' ', addr.road, addr.house_number), '')), addr.city)) AS location,\n\tCOUNT(*) AS total_recharges,\n\tCASE\n      WHEN SUM(charge_energy_added) < 1000 THEN SUM(charge_energy_added)::NUMERIC(4,0)::VARCHAR || ' kWh' \n      WHEN SUM(charge_energy_added) < 1000000 THEN (SUM(charge_energy_added) / 1000)::NUMERIC(9, 3)::VARCHAR || ' MWh' \n      WHEN SUM(charge_energy_added) >= 1000000 THEN (SUM(charge_energy_added) / 1000000)::NUMERIC(9, 3)::VARCHAR || ' GWh' \n   END as charge_energy_added, sum(cost) as cost\nFROM\n\tcharging_processes cp\nLEFT JOIN addresses addr ON cp.address_id = addr.id\nLEFT JOIN geofences geo ON cp.geofence_id = geo.id\nWHERE\n\tcp.id IN (\n\t\tSELECT c.charging_process_id \n\t  FROM charges c\n  \tLEFT JOIN charging_processes cp ON cp.id = c.charging_process_id\n  \tLEFT JOIN addresses addr ON addr.id = cp.address_id\n  \tLEFT JOIN geofences geo ON geo.id = geofence_id\n  \tWHERE \n  \t  $__timeFilter(cp.end_date)\n  \t\tAND c.fast_charger_present IS NOT true\n  \t\tAND c.charger_voltage != 2\n  \t\tAND cp.car_id = $car_id\n  \tGROUP BY 1\n\t)\nGROUP BY\n\t1\nORDER BY\n\tSUM(charge_energy_added) DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "AC stats",
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 15, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  inserted_at AS \"time\",\n  efficiency\nFROM cars\nWHERE\n  $__timeFilter(inserted_at)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ('$ac_stats'::json -> 'totalCost')::text::float  as total_cost,\n  ('$ac_stats'::json -> 'averageCost')::text::float  as average_cost"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ('$ac_stats'::json -> 'totalEnergy')::text::float  as total_energy,\n  ('$ac_stats'::json -> 'averageEnergy')::text::float  as average_energy"
    }
   ]
  },
  {
   "title": "Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ('$ac_stats'::json -> 'totalTime')::text::float  as total_time,\n  ('$ac_stats'::json -> 'averageTime')::text::float  as average_time"
    }
   ]
  }
 ]
}