{
 "title": "行驶能效Speed Rates",
 "tags": [
  "le个人汉化",
  "tesla"
 ],
 "time": { "from": "now-10y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC;"
   },
   {
    "name": "length_unit",
    "query": "select unit_of_length from settings limit 1;"
   },
   {
    "name": "preferred_range",
    "query": "select preferred_range from settings limit 1;"
   },
   {
    "name": "min_distance",
    "label": "min. distance per drive",
    "query": "1, 5, 10, 25, 50, 100, 150, 200"
   },
   {
    "name": "base_url",
    "query": "select base_url from settings limit 1;"
   }
  ]
 },
 "panels": [
  {
   "title": "Speed – Efficiency",
   "type": "table",
   "gridPos": { "h": 25, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH t AS (\r\n\tSELECT\r\n\t\tsum(start_ideal_range_km - end_ideal_range_km) AS total_ideal_range,\r\n\t\tsum(start_rated_range_km - end_rated_range_km) AS total_rated_range,\r\n\t\tsum(distance) AS total_distance,\r\n\t\tsum(duration_min) as duration,\r\n        CASE WHEN '$length_unit' = 'km' THEN 1 WHEN '$length_unit' = 'mi' THEN 1.60934 END AS distance_factor,\r\n\t\tcar_id\r\n\tFROM\r\n\t\tdrives \r\n\tWHERE\r\n\t  $__timeFilter(end_date)\r\n\t\tAND distance IS NOT NULL\r\n\t\tAND drives.car_id = $car_id\r\n\t\tAND convert_km(distance::numeric, '$length_unit') >= $min_distance \r\n\t\tAND start_[[preferred_range]]_range_km - end_[[preferred_range]]_range_km > 0.1\r\n\tGROUP BY id\r\n),  data AS (\r\n    SELECT\r\n        total_distance / total_rated_range AS efficiency,\r\n    \ttotal_rated_range / total_distance * c.efficiency * 1000 * distance_factor AS consumption_$length_unit,\r\n        convert_km(total_distance::numeric, 'km') AS total_distance_$length_unit,\r\n    \t(total_distance / duration) * 60 / distance_factor AS avg_speed_$length_unit\r\n    FROM t\r\n    JOIN cars c ON t.car_id = c.id\r\n)\r\nSELECT \r\n    ROUND(cast(avg_speed_$length_unit AS numeric) / 5, 0) * 5 AS avg_speed_$length_unit, \r\n    avg(efficiency) AS efficiency, \r\n    avg(consumption_$length_unit) AS consumption_$length_unit, \r\n    avg(total_distance_$length_unit) AS avg_distance_$length_unit,\r\n    min(total_distance_$length_unit) AS min_distance_$length_unit, \r\n    max(total_distance_$length_unit) AS max_distance_$length_unit\r\nFROM data\r\nGROUP BY 1\r\nORDER BY 1 DESC;"
    }
   ]
  },
  {
   "title": "记录里程",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select convert_km(sum(distance)::numeric, '$length_unit') as \"distance_$length_unit\" \nfrom drives \nwhere $__timeFilter(end_date) and car_id = $car_id;"
    }
   ]
  },
  {
   "title": "Current $preferred_range efficiency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tCASE WHEN '$length_unit' = 'km' THEN efficiency\n\t     WHEN '$length_unit' = 'mi' THEN efficiency * 1.60934\n\tEND * 1000 as \"efficiency_$length_unit\"\nFROM\n\tcars\nWHERE\n\tid = $car_id;"
    }
   ]
  },
  {
   "title": "Consumption (net)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select \n  sum((start_[[preferred_range]]_range_km - end_[[preferred_range]]_range_km) * cars.efficiency) / sum(distance) * 1000 * \n    CASE WHEN '$length_unit' = 'km' THEN 1\n         WHEN '$length_unit' = 'mi' THEN 1.60934\n    END AS \"consumption_$length_unit\"\nfrom drives \ninner join cars on cars.id = car_id\nwhere $__timeFilter(end_date) \n  and distance is not null and\n  start_[[preferred_range]]_range_km - end_[[preferred_range]]_range_km >= 0.1 and\n  car_id = $car_id"
    }
   ]
  },
  {
   "title": "Consumption (gross) ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "WITH d1 AS (\n\tSELECT\n\t\tc.car_id,\n\t\tlag(end_[[preferred_range]]_range_km) OVER (ORDER BY start_date) - start_[[preferred_range]]_range_km AS range_loss,\n\t\tp.odometer - lag(p.odometer) OVER (ORDER BY start_date) AS distance\n\tFROM\n\t\tcharging_processes c\n\tLEFT JOIN positions p ON p.id = c.position_id \n\tWHERE\n\t  $__timeFilter(end_date)\n\t  and end_date IS NOT NULL AND\n\t  c.car_id = $car_id\n\tORDER BY\n\t\tstart_date\n),\nd2 AS (\nSELECT\n\tcar_id,\n\tsum(range_loss) AS range_loss,\n\tsum(distance) AS distance\nFROM\n\td1\nWHERE\n\tdistance > 0 AND range_loss >= 0\nGROUP BY\n\tcar_id\n)\nSELECT\nrange_loss * c.efficiency / distance * 1000 *\n  CASE WHEN '$length_unit' = 'km' THEN 1\n       WHEN '$length_unit' = 'mi' THEN 1.60934\n  END AS \"consumption_$length_unit\"\nFROM\n\td2\n\tLEFT JOIN cars c ON c.id = car_id"
    }
   ]
  },
  {
   "title": "最高速度",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH speed_summary AS (\r\n    SELECT ROUND(convert_km(speed_max::numeric, '$length_unit') / 10, 0) * 10 AS speed_$length_unit\r\n    FROM drives\r\n    WHERE \r\n        $__timeFilter(end_date)\r\n        AND car_id = $car_id\r\n        AND end_date IS NOT NULL\r\n    GROUP BY id\r\n)\r\nSELECT speed_[[length_unit]], COUNT(speed_[[length_unit]]) AS n\r\n  FROM speed_summary\r\n  WHERE speed_$length_unit > 0\r\n  GROUP BY 1\r\n  ORDER BY 1 DESC"
    }
   ]
  }
 ]
}